#!/bin/sh
set -eu

IMAGE_NAME="${1:-diffed-places/pipeline}"
IMAGE_DIGEST="${2:-sha256:unknown}"
DEFAULT_TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TIMESTAMP="${3:-$DEFAULT_TIMESTAMP}"
PIPELINE_SBOM="artifacts/pipeline.cdx.json"
TIPPECANOE_SBOM="artifacts/tippecanoe.cdx.json"
OUTPUT="artifacts/container.cdx.json"

if command -v uuidgen > /dev/null 2>&1; then
  SERIAL="urn:uuid:$(uuidgen | tr '[:upper:]' '[:lower:]')"
elif [ -r /proc/sys/kernel/random/uuid ]; then
  SERIAL="urn:uuid:$(cat /proc/sys/kernel/random/uuid)"
else
  echo "Error: cannot generate UUID — install uuidgen (apk add util-linux)" >&2
  exit 1
fi

jq -n \
  --arg serial       "$SERIAL" \
  --arg image        "$IMAGE_NAME" \
  --arg digest       "$IMAGE_DIGEST" \
  --arg timestamp    "$TIMESTAMP" \
  --slurpfile pipeline   "$PIPELINE_SBOM" \
  --slurpfile tippecanoe "$TIPPECANOE_SBOM" \
'
($pipeline[0].metadata.component)                              as $meta_pipeline      |
($tippecanoe[0].metadata.component)                            as $meta_tippecanoe    |
($meta_pipeline   | (.["bom-ref"] // .name))                   as $ref_pipeline       |
($meta_tippecanoe | (.["bom-ref"] // .name))                   as $ref_tippecanoe     |
($tippecanoe[0].components // [] | map(.["bom-ref"] // .name)) as $deps_of_tippecanoe |
($pipeline[0].components   // [] | map(.["bom-ref"] // .name)) as $deps_of_pipeline   |

# Collect all known component bom-refs so we can filter out
# dependency entries that reference undeclared components
(
  [$image, $ref_pipeline, $ref_tippecanoe] +
  ($pipeline[0].components   // [] | map(.["bom-ref"] // .name)) +
  ($tippecanoe[0].components // [] | map(.["bom-ref"] // .name))
) as $known_refs |

# Carry forward inner deps from each sub-SBOM:
# - drop the sub-SBOMs own root entry (now represented at container level)
# - drop any entry whose ref is not a known component (stray entries)
# - deduplicate by ref (keep first occurrence)
(
  ($tippecanoe[0].dependencies // [] | map(select(.ref != $ref_tippecanoe))) +
  ($pipeline[0].dependencies   // [] | map(select(.ref != $ref_pipeline)))
  | map(select(.ref as $r | $known_refs | index($r) != null))
  | reduce .[] as $dep (
      [];
      if (map(.ref) | index($dep.ref)) == null then . + [$dep] else . end
    )
) as $inner_deps |

{
  bomFormat:    "CycloneDX",
  specVersion:  "1.7",
  version:      1,
  serialNumber: $serial,

  metadata: {
    timestamp: $timestamp,
    supplier: {
      name: "Diffed Places",
      url:  ["https://github.com/diffed-places/"]
    },
    lifecycles: [{phase: "build"}],
    component: {
      type:      "container",
      "bom-ref": $image,
      name:      $image,
      version:   $digest
    }
  },

  components: [
    ($meta_pipeline + {
      "bom-ref":  $ref_pipeline,
      type:       "application",
      components: ($pipeline[0].components // [])
    }),
    ($meta_tippecanoe + {
      "bom-ref":  $ref_tippecanoe,
      type:       "application",
      components: ($tippecanoe[0].components // [])
    })
  ],

  dependencies: (
    [
      {
        "ref":       $image,
        "dependsOn": [$ref_tippecanoe, $ref_pipeline]
      },
      {
        "ref":       $ref_tippecanoe,
        "dependsOn": $deps_of_tippecanoe
      },
      {
        "ref":       $ref_pipeline,
        "dependsOn": ($deps_of_pipeline + [$ref_tippecanoe])
      }
    ] + $inner_deps
  ),

  compositions: [
    {
      "aggregate":  "complete",
      "assemblies": [$ref_tippecanoe],
      "comment":    "All statically linked dependencies enumerated via apk info"
    },
    {
      "aggregate":  "complete",
      "assemblies": [$ref_pipeline],
      "comment":    "Generated by cargo-cyclonedx"
    }
  ]
}
' > "$OUTPUT"

echo "Written: $OUTPUT"
